### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ckaj** [Norbit4/DiscordMc#1]
Hi, i uploaded plugin to my server and the plugin is not working. 
![image](https://user-images.githubusercontent.com/97398441/188261626-f86531dd-e325-43c1-8dab-0db6f0c036af.png)
I did only the thing that i pasted token into my config, allowed sync ranks and translated things like Uptime etc. Plugin not working since upload

**Comment by ckaj** [comment]
Version of server: Paper 1.17.1

**Comment by Norbit4** [comment]
send me your config.yml

**Comment by ckaj** [comment]
https://mclo.gs/6E0e5TJ
[config.txt](https://github.com/Norbit4/DiscordMc/files/9485303/config.txt)
i renamed the config because .yml is not supported by github

**Comment by Norbit4** [comment]
you need add server id:

```yml 
//config.yml
discord-server-id: '' <- THIS
```
#

if you enebled module, you need add channel for this module

_for example discord chat module:_

```yml 
#---------------------------------------#
#         [discord-chat-module]         #
#---------------------------------------#
# help: https://github.com/Norbit4/DiscordMc/wiki/Chat-module

discord-chat-module: true
channel-chat-id: '' <- CHANNEL ID
```

more about inital configuaration here: 
- https://github.com/Norbit4/DiscordMc/wiki/Configuration
